from ..models.idea_generation_model import ActivityIdea
from ..models.context_model import Context
from ollama import chat, ChatResponse
import json

SYSTEM_PROMPT = """
You are the Synthesis Agent for a care-home activity planning AI.
Your job is to take:
- The validated context
- A list of generated activity ideas

…and return a clear, structured, warm, concise final output for the end-user (a care assistant).

Rules:
- Do NOT add new activity ideas.
- Do NOT remove or filter activity ideas.
- Do NOT alter the meaning of any idea.
- You may expand ideas slightly for clarity.
- Keep tone professional, supportive, and simple.
- Make the output suitable for real carers in care homes."""

USER_PROMPT_TEMPLATE = """
The following is the context for the activity planning:
{context}

These are the activity ideas generated by the Idea Generator Agent:
{ideas}

Please synthesise these into a clear, well-structured final answer.
Use the following structure:

1. Summary of the Context
2. Activity Ideas (list each idea with a 2–3 sentence explanation)
3. Why These Ideas Fit the Context (brief paragraph)
4. Optional Notes for the Activities Coordinator (tips, considerations—no risk assessment)

Remember: do not add, remove, or rank ideas."""

class SynthesisAgent:
    def __init__(
            self, 
            system_prompt: str | None = None,
            user_prompt_template: str | None = None,
        ):
        if system_prompt is None:
            system_prompt = SYSTEM_PROMPT
        self.system_prompt = system_prompt
        if user_prompt_template is None:
            user_prompt_template = USER_PROMPT_TEMPLATE
        self.user_prompt_template = user_prompt_template

    def _generate_user_prompt(
            self, 
            context: Context,
            ideas: list[ActivityIdea],
        ) -> str:
        return self.user_prompt_template.format(
            context=context.model_dump_json(indent=2),
            ideas=json.dumps([idea.model_dump() for idea in ideas], indent=2)
        )

    def run(self, context: Context, ideas: list[ActivityIdea], model_id: str = 'qwen3:8b') -> str:
        user_prompt = self._generate_user_prompt(
            context=context,
            ideas=ideas
        )
        response: ChatResponse = chat(
            model=model_id,
            messages=[
                {'role': 'system', 'content': self.system_prompt},
                {'role': 'user', 'content': user_prompt},
            ],
            options={"temperature": 0.0}
        )

        response: ChatResponse = chat(
            model=model_id,
            messages=[
                {'role': 'system', 'content': self.system_prompt},
                {'role': 'user', 'content': user_prompt},
            ]
        )

        return response.message.content